class Emoji{
  String name;
  String path;
  String category;
  bool isSelected = false;

  Emoji({required this.name, required this.path, required this.category});
}
List<Emoji> emojis = [
  Emoji(name: 'Amusement', path: 'Amusement.png', category: 'Positive'),
  Emoji(name: 'Delight', path: 'Delight.png', category: 'Positive'),
  Emoji(name: 'Elation', path: 'Elation.png', category: 'Positive'),
  Emoji(name: 'Excitement', path: 'Excitement.png', category: 'Positive'),
  Emoji(name: 'Happiness', path: 'Happiness.png', category: 'Positive'),
  Emoji(name: 'Joy', path: 'Joy.png', category: 'Positive'),
  Emoji(name: 'Pleasure', path: 'Pleasure.png', category: 'Positive'),
  Emoji(name: 'Affection', path: 'Affection.png', category: 'Positive'),
  Emoji(name: 'Caring', path: 'Caring.png', category: 'Positive'),
  Emoji(name: 'Empathy', path: 'Empathy.png', category: 'Neutral'),
  Emoji(name: 'Friendliness', path: 'Friendliness.png', category: 'Positive'),
  Emoji(name: 'Love', path: 'Love.png', category: 'Positive'),
  Emoji(name: 'Agitation', path: 'Agitation.png', category: 'Negative'),
  Emoji(name: 'Shock', path: 'Shock.png', category: 'Negative'),
  Emoji(name: 'Stress', path: 'Stress.png', category: 'Negative'),
  Emoji(name: 'Tension', path: 'Tension.png', category: 'Negative'),
  Emoji(name: 'Anger', path: 'Anger.png', category: 'Negative'),
  Emoji(name: 'Annoyance', path: 'Annoyance.png', category: 'Negative'),
  Emoji(name: 'Contempt', path: 'Contempt.png', category: 'Negative'),
  Emoji(name: 'Disgust', path: 'Disgust.png', category: 'Negative'),
  Emoji(name: 'Irritation', path: 'Irritation.png', category: 'Negative'),
  Emoji(name: 'Anxiety', path: 'Anxiety.png', category: 'Negative'),
  Emoji(name: 'Embarrassment', path: 'Embarrassment.png', category: 'Negative'),
  Emoji(name: 'Fear', path: 'Fear.png', category: 'Negative'),
  Emoji(name: 'Helplessness', path: 'Helplessness.png', category: 'Negative'),
  Emoji(name: 'Powerlessness', path: 'Powerlessness.png', category: 'Negative'),
  Emoji(name: 'Worry', path: 'Worry.png', category: 'Negative'),
  Emoji(name: 'Boredom', path: 'Boredom.png', category: 'Neutral'),
  Emoji(name: 'Despair', path: 'Despair.png', category: 'Negative'),
  Emoji(name: 'Disappointment', path: 'Disappointment.png', category: 'Negative'),
  Emoji(name: 'Hurt', path: 'Hurt.png', category: 'Negative'),
  Emoji(name: 'Sadness', path: 'Sadness.png', category: 'Negative'),
  Emoji(name: 'Doubt', path: 'Doubt.png', category: 'Negative'),
  Emoji(name: 'Envy', path: 'Envy.png', category: 'Neutral'),
  Emoji(name: 'Frustration', path: 'Frustration.png', category: 'Negative'),
  Emoji(name: 'Guilt', path: 'Guilt.png', category: 'Negative'),
  Emoji(name: 'Pride', path: 'Pride.png', category: 'Negative'),
  Emoji(name: 'Shame', path: 'Shame.png', category: 'Negative'),
  Emoji(name: 'Courage', path: 'Courage.png', category: 'Positive'),
  Emoji(name: 'Hope', path: 'Hope.png', category: 'Positive'),
  Emoji(name: 'Humility', path: 'Humility.png', category: 'Positive'),
  Emoji(name: 'Satisfaction', path: 'Satisfaction.png', category: 'Positive'),
  Emoji(name: 'Trust', path: 'Trust.png', category: 'Positive'),
  Emoji(name: 'Calmness', path: 'Calmness.png', category: 'Neutral'),
  Emoji(name: 'Contentment', path: 'Contentment.png', category: 'Positive'),
  Emoji(name: 'Relaxation', path: 'Relaxation.png', category: 'Positive'),
  Emoji(name: 'Relief', path: 'Relief.png', category: 'Neutral'),
  Emoji(name: 'Serenity', path: 'Serenity.png', category: 'Positive'),
  Emoji(name: 'Interest', path: 'Interest.png', category: 'Neutral'),
  Emoji(name: 'Politeness', path: 'Politeness.png', category: 'Neutral'),
  Emoji(name: 'Surprise', path: 'Surprise.png', category: 'Crazy'),

];